In [41]:
import numpy as np
import pandas as pd
import tensorflow
from keras.models import Sequential
from keras import layers
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [47]:
data = pd.read_csv('data.txt')

In [48]:
data.head()

1
0  ای رستخیز ناگهان، وی رحمت بی منتها\tای آتشی اف...
1  امروز خندان آمدی، مفتاح زندان آمدی\tبر مستمندا...
2  خورشید را حاجب تویی، امید را واجب تویی\tمطلب ت...
3  در سینه ها برخاسته، اندیشه را آراسته\tهم خویش ...
4  ای روح بخش بی بَدَل، وی لذتِ علم و عمل\tباقی ب...

In [49]:
with open('stopwords.txt') as stopwords_file:
  stopwords = stopwords_file.readlines()
stopwords = [line.replace('\n', '') for line in stopwords] 

In [50]:
stopwords[0:20]

['!',
 '"',
 '#',
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '/',
 ':',
 '[',
 ']',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'آباد',
 'آخ']

In [51]:
len(stopwords)

1816

In [52]:
text = [line.replace('\t', ' ') for line in data.values.flatten()]
text = [line.replace('-', ' ') for line in text]

In [53]:
!pip install hazm
from hazm import word_tokenize

In [65]:
word_tokenized = [word_tokenize(t) for t in text]
word_tokenized_filtered = [[w for w in sentence if w not in stopwords] for sentence in word_tokenized]

In [55]:
#example
word_tokenized_filtered[14]

['کوه',
 'غمت',
 'بشکافته',
 'وآن',
 'غم',
 'دل',
 'درتافته',
 'قطره',
 'خونی',
 'فضلت',
 'افضال']

In [56]:
vocab_len = 0
for sentence in word_tokenized_filtered:
    vocab_len += len(sentence)

In [57]:
vocab_len

42271

In [73]:
sentences = []
for sentence in word_tokenized_filtered:
  sentences.append(' '.join(sentence))

In [75]:
sentences[0]

'رستخیز رحمت منتها آتشی افروخته بیشه اندیشه'

In [58]:
max_len = 1000
model = Sequential()
model.add(layers.Embedding(vocab_len, 50,input_shape=(vocab_len,)))
model.add(layers.Flatten())
model.add(layers.Dense(10, activation='relu'))
model.add(layers.Dense(vocab_len, activation='softmax'))

In [59]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 42271, 50)         2113550   
                                                                 
 flatten_1 (Flatten)         (None, 2113550)           0         
                                                                 
 dense_2 (Dense)             (None, 10)                21135510  
                                                                 
 dense_3 (Dense)             (None, 42271)             464981    
                                                                 
Total params: 23,714,041
Trainable params: 23,714,041
Non-trainable params: 0
_________________________________________________________________


In [76]:
encoded_vocab = [one_hot(sentence, vocab_len) for sentence in sentences] 

In [77]:
len(encoded_vocab)

5816

In [85]:
max_length = 15
padded_reviews = pad_sequences(encoded_vocab, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 1507 23952 37559 ...     0     0     0]
 [32822 11606 33977 ...     0     0     0]
 [18293 21039  9160 ...     0     0     0]
 ...
 [18408 13190 20455 ...     0     0     0]
 [ 4022  9834 40478 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]


In [88]:
X = padded_reviews

In [90]:
#model.fit(X, epochs=50, verbose=0)